### PR TITLE
Django 2.0 support: don't use the removed _get_val_from_obj()

### LINKED ISSUE #101: Field._get_val_from_obj() is removed in Django 2.0
This method was deprecated for a long time, and was removed in upcoming Django 2.0:
See https://code.djangoproject.com/ticket/24716

To reproduce, checkout the latest Django 2.0 branch, and try to edit `UserSocialAuth` object from the admin interface.

social-app-django is currently using it inside `JSONField` wrapper

### PR DESCRIPTION
**Pull request by muodov**
Fix #101

### CODE REVIEW

**Comment by muodov** [comment]
If I'm not mistaken, `JSONField` is optional and only makes sense for Postgres backend.
It might be a good idea to re-use `value_from_object()` from the base class (whatever is chosen), instead of the `getattr(obj, self.attname)`. What do you think, @fengsi ?

**Comment by fengsi** [comment]
@muodov that's what I meant - `getattr(obj, self.attname)` is more like a hack as it's not using any documented public API of Django.  Yeah if we could somehow `super()` the `value_from_object()` from the base class, that'll be great.
And that's also why I mentioned `JSONField` - I meant since it could be `TextField` or `JSONField`, and if it were `JSONField`, the `get_prep_value()` method then becomes unnecessary, because there is no need to dump anything (`JSONField` already does it).

**Comment by muodov** [comment]
@fengsi I've updated the PR according to your remark

**Comment by Speedy1991** [comment]
Is it possible to release a bugfix with this PR as soon as possible, because it breaks the admin interface?

**Comment by muodov** [comment]
I guess it depends on @omab :)

**Comment by chaoranxie** [comment]
just wondering when will the new version of social-app-django be pushed to pypi, i am only seeing the old one here https://pypi.python.org/pypi/social-auth-app-django/ Thanks

**Comment by omab** [comment]
@chaoranxie, version `2.1.0` published in pypi.

**Pull request merged**
