### PR TITLE
Move to Black

### PR DESCRIPTION
**Pull request by pfouque**
## Proposed changes

Move to Black formatting

## Types of changes

Please check the type of change your PR introduces:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Code style update (PEP8, lint, formatting, renaming, etc)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes (build process, tests runner, etc)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [X] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Other information

Any other information that is important to this PR such as screenshots of how
the component looks before and after the change.

### CODE REVIEW

**Review by atodorov — APPROVED** [review]
LGTM

**Comment by pfouque** [comment]
Thanks! I will check the CI then!

**Comment by pfouque** [comment]
I noticed CI is checking, perhaps I should add black too.

**Comment by nijel** [comment]
Black is included via pre-commit. The flake8 is standalone to provide feedback via GitHub.

**Review by nijel — APPROVED** [review]
LGTM

**Pull request merged**
