### PR TITLE
Add more view tests.

### PR DESCRIPTION
**Pull request by andreif**
✅ Ready for review.

### CODE REVIEW

**Comment by andreif** [comment]
Weirdly enough https://github.com/python-social-auth/social-app-django/pull/93/commits/3b6247bbf09a1d643569fbac4944d6699adabd74 fails in my fork https://travis-ci.org/andreif/social-app-django/builds/291074547
There are no other commits pushed to master so I am not sure what is going on.

**Comment by andreif** [comment]
Anyway, https://github.com/python-social-auth/social-app-django/pull/93/commits/c1e2795b00b753d58a81fa6a0261d8dae1d9c73d is passing in my fork (https://travis-ci.org/andreif/social-app-django/builds/291077234) so the PR is now ready for review.

**Comment by andreif** [comment]
@omab Have you set environmental variables in Travis settings for the repo? Still wondering why intermediate commits fail in my fork but pass here... It can happen due to merge, but there were no commits to master after branching out, so it's kinda mysterious.

**Comment by omab** [comment]
@andreif, I didn't set any env vars in travis, a restart of those jobs did the trick, I've seen an increase of false positive failures lately on Travis.

**Comment by omab** [comment]
Thanks!

**Pull request merged**
