### PR TITLE
models: Use Django native JSONField

### LINKED ISSUE #209: JSONField with JSONFieldBase from postgress doesn't support filtering
I don't know is it intended behavior or not, but I got `django.db.utils.ProgrammingError` when I was trying to simple filter UserSocialAuth by `acces_token` from `extra_data`.

### Steps to reproduce

```
from social_django.models import UserSocialAuth

UserSocialAuth.objects.filter(extra_data__access_token="example")
```
traceback
```
psycopg2.ProgrammingError: operator does not exist: text -> unknown
LINE 1: ... WHERE ("social_auth_usersocialauth"."extra_data" -> 'access...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```

`SOCIAL_AUTH_POSTGRES_JSONFIELD` is set up to `True`

### LINKED ISSUE #464: Django 4.2.2 breaks the way JSONField behaves
### Expected behaviour

When using social-app-django's  `extra_data`, prior to Django 4.2.2, the extra data was saved as a dict. 

### Actual behaviour

With 4.2.2 it is saved as a string instead. 

### What are the steps to reproduce this issue?

Perform a normal login using a backend that uses extra data, such as SAML.

### Any logs, error output, etc?

With Django 4.2.2, and a stack that look like this:

stack

the code at https://github.com/python-social-auth/social-app-django/blob/8d0a2052d1b22a899454571c62237d23aa25af97/social_django/storage.py#L24 ends up behaving as follows:

1.  On entry to the two new lines of code added in Django, `value` is a dict, but is flattened into a string by the new code.
2. The call to `save()` then ends up saving a string instead of the dict.

See also the bug I originally filed against Django for this at https://code.djangoproject.com/ticket/34644.

### Any other comments?

The referenced Django bug contains suggestions from the Django team on what changes might be needed in social-app-django.

### PR DESCRIPTION
**Pull request by nijel**
## Proposed changes

It was introduced in Django 3.1 and social_django already requires Django 3.2.

Fixes #464
Fixes #209

## Types of changes

Please check the type of change your PR introduces:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (PEP8, lint, formatting, renaming, etc)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build related changes (build process, tests runner, etc)
- [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask. We're here to
help! This is simply a reminder of what we are going to look for before merging
your code._

- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

## Other information

Any other information that is important to this PR such as screenshots of how
the component looks before and after the change.

### CODE REVIEW

**Comment by ShaheedHaque** [comment]
I have tested the branch. First, I ran the old code and verified that the `extra_data` was a string:

```
>>> from social_django.models import UserSocialAuth
>>> UserSocialAuth.objects.all()[0].extra_data
'{"auth_time": 1686390682, "session_index": "_dWXC7z0-o8ffbl8Dm-bPV8B3bxVpeHvp", "name_id": "auth0|62ce80da6379e9972defbebe", "idp_name": "28361fbf-666b-4ae2-b5f1-0366258f78bc", "idp_display_name": "Acme - auth0.com", "idp_logo": "https://login.paiyroll.com/static/images/paiyroll.001.png"}'
>>> type(UserSocialAuth.objects.all()[0].extra_data)
<class 'str'>
```

I then ran the migrations from this commit, and the `extra_data` is now, correctly, a dict:

```
>>> from social_django.models import UserSocialAuth
>>> UserSocialAuth.objects.all()[0].extra_data
{'name_id': 'auth0|62ce80da6379e9972defbebe', 'idp_logo': 'https://login.paiyroll.com/static/images/paiyroll.001.png', 'idp_name': '28361fbf-666b-4ae2-b5f1-0366258f78bc', 'auth_time': 1686390682, 'session_index': '_dWXC7z0-o8ffbl8Dm-bPV8B3bxVpeHvp', 'idp_display_name': 'Acme - auth0.com'}
>>> type(UserSocialAuth.objects.all()[0].extra_data)
<class 'dict'>
```

Finally, I ran our system test which caught the issue, and it now passes.

So, this change LGTM: thanks!

**Comment by rib3** [comment]
Would it be possible to cut a release with this change?

**Comment by parberge** [comment]
Couldn't find any information about this in the release, so I'll ask here:

Does this mean we should remove `SOCIAL_AUTH_JSONFIELD_ENABLED` from settings if we update to 5.3.0?
Also I wonder if https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#json-field-support should be updated as well?

I see 5.2.0 is still the "latest" according to releases here on github. But on pypi it's 5.3.0

**Comment by nijel** [comment]
> Does this mean we should remove SOCIAL_AUTH_JSONFIELD_ENABLED from settings if we update to 5.3.0?

Once you upgrade, it is still used during the migration.

> Also I wonder if https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#json-field-support should be updated as well?

Yes it should, contributions are welcome.

> I see 5.2.0 is still the "latest" according to releases here on github. But on pypi it's 5.3.0

I forgot to tick “Set as the latest release”, fixed now.

**Pull request merged**
